### ISSUE TITLE
Enabling EndpointRouting in ASP.NET Core 2.2 will cause LightInject errors

### ISSUE THREAD

**Issue by alexthissen** [seesharper/LightInject.Microsoft.AspNetCore.Hosting#24] opened 2019-05-29 13:14 UTC
Same is true when setting the compatibility version to 2.2 explicitly in an ASP.NET Core 2.2 project.

Exception that occurs is:

An unhandled exception occurred while processing the request.
InvalidOperationException: Attempt to create a disposable instance without a current scope.
LightInject.PerRequestLifeTime.TrackInstance(Scope scope, IDisposable disposable) in LightInject.cs, line 6229

Repro: Create a new ASP.NET Core 2.2 project and follow instructions as in 
https://www.lightinject.net/microsoft.aspnetcore.hosting/

in Startup.ConfigureServices add either of the following:
services.AddMvc(options => options.EnableEndpointRouting = true)
                .AddControllersAsServices();

or 
services.AddMvc()
                .AddControllersAsServices()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

Run the project. Exception as indicated above occurs.

**Comment by seesharper** [comment] 2019-05-30 18:32
Hi @alexthissen and thanks for reporting this.
I was however not able to reproduce the error. Could you create a simple repo and push it up on GitHub.

**Comment by alexthissen** [comment] 2019-06-03 10:22
Hi back @seesharper!
I put a repro repo here: https://github.com/alexthissen/LightInjectBugRepro.
Hope it helps you reproduce the bug.

**Comment by seesharper** [comment] 2019-06-03 13:25
Hi again and thanks for providing a repro 👍

I am however unable to reproduce the bug. Maybe this is related to hosting?

How do you run this? Is it through IIS?

**Comment by alexthissen** [comment] 2019-06-06 18:23
Did some experiments and it is for IIS Express hosting that the bug occurs. Self-hosted seems to be fine.

**Comment by seesharper** [comment] 2019-06-06 19:15
Thanks a lot. I had a feeling it might be some hosting issue. I'll have a look

**Comment by seesharper** [comment] 2019-06-06 19:31
@alexthissen Do you see the same issue on full IIS?

**Comment by alexthissen** [comment] 2019-06-06 19:56
Haven't checked. Will do that later

**Comment by seesharper** [comment] 2019-08-27 20:27
Fixed in LightInject.Microsoft.AspNetCore.Hosting 1.2.1 👍

**Closed by seesharper** 2019-08-27 20:27 UTC
